openapi: 3.0.1
info:
  title: Charts Generator ChatGPT Plugin
  description: A plugin that creates ECharts based on user input or URL content.
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /charts:
    post:
      operationId: createChart
      summary: Create an EChart based on a JSON options object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: ECharts options object
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  htmlPath:
                    type: string
                    description: Path to the generated HTML file
                  imgPath:
                    type: string
                    description: Path to the generated PNG image
